### ISSUE TITLE
Typo in nytextract.py, line 95

### ISSUE THREAD

**Issue by KatarinaRagna** [notnews/nytimes-corpus-extractor#1]
Replace line 95:
('Taxonomic Classifiers', 'String', 'Multiple', '/nitf/head/docdata/identified-content/classifier[@class="online_producer" and @type="taxinomic_classifier"]'),

with
('Taxonomic Classifiers', 'String', 'Multiple', '/nitf/head/docdata/identified-content/classifier[@class="online_producer" and @type="taxonomic_classifier"]'),

otherwise this metadata field will not be found.

**Comment by soodoku** [comment]
Thanks for catching this.

**Comment by KatarinaRagna** [comment]
Found yet another two, line 68 and 97, both must be "identified-content" instead of "identifiedcontent".
Cheers!

**Comment by soodoku** [comment]
excellent. thanks!
