### ISSUE TITLE
Cannot find requirements.txt

### ISSUE THREAD

**Issue by msstefo** [notnews/nytimes-corpus-extractor#4]
Hey guys, I am new to python and have difficulties with running the script.

 the command "pip install -r requirements.txt" retrieves the error message "Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'"

After installing lxml 3.1.1 as well as trying with lxml 4.1.1 another way, the file "nytextract.py" cannot be found either. 

Can you help me out here please?

**Comment by soodoku** [comment]
Not sure what you are doing. Clone the repo. And then when you are in the folder run pip install -r 

requrements.txt is one of the files hosted here as you can see:
https://github.com/notnews/nytimes-corpus-extractor

again I think you just are in the wrong folder if you can't see the python file.
